# Digital Ocean App Platform Specification
# Deploy with: doctl apps create --spec app.yaml

name: for-classification-app
region: nyc3

# Automatic deployment from GitHub
github:
  repo: quazini/DEAKIN-UNI-FoR-Classification
  branch: main
  deploy_on_push: true

services:
  - name: streamlit

    # Docker build configuration
    dockerfile_path: Dockerfile
    source_dir: /

    # Instance configuration
    instance_size_slug: basic-xs  # $5/month (512 MB RAM, 1 vCPU)
    instance_count: 1

    # HTTP configuration
    http_port: 8501

    # Routes
    routes:
      - path: /
        preserve_path_prefix: false

    # Health check
    health_check:
      http_path: /_stcore/health
      initial_delay_seconds: 10
      period_seconds: 30
      timeout_seconds: 10
      success_threshold: 1
      failure_threshold: 3

    # Environment variables
    envs:
      # Streamlit configuration
      - key: STREAMLIT_SERVER_PORT
        value: "8501"
        type: PLAIN

      - key: STREAMLIT_SERVER_ADDRESS
        value: "0.0.0.0"
        type: PLAIN

      - key: STREAMLIT_SERVER_HEADLESS
        value: "true"
        type: PLAIN

      - key: STREAMLIT_BROWSER_GATHER_USAGE_STATS
        value: "false"
        type: PLAIN

      # Application settings
      - key: APP_NAME
        value: "FoR Classification System"
        type: PLAIN

      - key: APP_ENV
        value: "production"
        type: PLAIN

      - key: SESSION_TIMEOUT_MINUTES
        value: "60"
        type: PLAIN

      # Webhook configuration
      - key: DEFAULT_WEBHOOK_URL
        value: "https://mbcrc.app.n8n.cloud/webhook/530ec5fa-656a-4c9c-bb05-5be7ff3bdef2"
        type: PLAIN

      # Sensitive environment variables (set via DO App Platform UI or CLI)
      - key: SUPABASE_URL
        type: SECRET
        value: "SUPABASE_URL"

      - key: SUPABASE_KEY
        type: SECRET
        value: "SUPABASE_KEY"

      - key: ADMIN_EMAIL
        type: SECRET
        value: "ADMIN_EMAIL"

    # Alerts
    alerts:
      - rule: DEPLOYMENT_FAILED
      - rule: DOMAIN_FAILED
      - rule: DEPLOYMENT_LIVE

    # Auto-scaling (optional, requires higher tier)
    # autoscaling:
    #   min_instance_count: 1
    #   max_instance_count: 3
    #   metrics:
    #     cpu:
    #       percent: 80

    # Logs
    log_destinations:
      - name: streamlit-logs
        papertrail:
          endpoint: syslog+tls://logs.papertrailapp.com:12345

# Domain configuration (optional - commented out to use DO provided URL)
# Uncomment and configure below if you want to add a custom domain later
# domains:
#   - domain: your-domain.com
#     type: PRIMARY
#     zone: your-domain.com

# Database (if needed - using external Supabase in this case)
# databases:
#   - name: postgres
#     engine: PG
#     version: "15"
#     size: db-s-dev-database
#     num_nodes: 1

# Static site (optional - for landing page)
# static_sites:
#   - name: landing
#     source_dir: /landing
#     build_command: npm run build
#     output_dir: dist
#     routes:
#       - path: /
#     envs:
#       - key: NODE_ENV
#         value: production