# Supabase Configuration
# Copy this file to secrets.toml and fill in your actual credentials

[connections.supabase]
SUPABASE_URL = "https://esgwrqcyhtzcsbepvqhc.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVzZ3dycWN5aHR6Y3NiZXB2cWhjIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NDM3NDk0NSwiZXhwIjoyMDY5OTUwOTQ1fQ.EcPegwutpaLvhU5c7RmqeyUXt-_-GELKS0_Sr-C04hA"

[admin]
# Admin email for first-time setup
ADMIN_EMAIL = "nanvenfaden@gmail.com"

[neo4j]
NEO4J_URI = "neo4j+s://87e196fc.databases.neo4j.io"
NEO4J_USERNAME = "neo4j"
NEO4J_PASSWORD = "JowDt6F_7RoEhmLd8IYCpXdUkUbhvSbPjOhHsTehJkY"
NEO4J_DATABASE = "neo4j"

[app]
# Application settings
APP_NAME = "app.py"
SESSION_TIMEOUT_MINUTES = 60